### ISSUE TITLE
유사도 측정

### ISSUE THREAD

**Issue by minhyeoky** [capstone-willson/chatbot-backend#1]
bert(multilingual) model pooled layer (768,) vector를 사용해 sentence간의 유사도 비교.
![image](https://user-images.githubusercontent.com/12870549/54515003-f70d1180-499e-11e9-8cad-fe305121e126.png)
맨하탄 거리, 유클리드 거리, 코사인 각도 3가지 방법으로 분석,
- 유클리드, 맨하탄 둘 다 비슷한 결과를 보여줌, 직선거리가 중요하냐 아니냐 인데, 좀 더 많은 케이스를 봐야 할 듯
- 코사인 각도의 경우 모든 벡터가 응집되어 있음 사용 X
- 형태소 분석 후 자카드 분석 가능

![image](https://user-images.githubusercontent.com/12870549/54514983-e2c91480-499e-11e9-9752-5243acf55540.png)

**테스트**
1.  질문의 길이에 큰 영향을 받지 않는지 - ok
2. 줄임말을 알아 듣는지 - no
3. 단어만을 물어 본다면 - ok

**문제점**
1.  단 9 개의 문장과 비교하는데, 3초가 걸림
2. ?의 개수에 민감, 있고 없고가 큼
3. 단어 만 입력했을 때 거리가 멂(현재는 괜찮지만 후엔)
4. 장학금 제도란 단어를 잘 알아 듣지 못함

**개선**
리그베다위키 및 나무위키 말뭉치를 사용, 형태소 분석, 품사 정보 주입, bert 직접 학습.
질문 형태소 분석
유사도 문장리스트 클러스터링 후 대표 벡터 생성

**Comment by taeuk-gang** [comment]
3초.... 선생님 훌륭합니다 👏 👏 👏

**Comment by minhyeoky** [comment]
> 3초.... 선생님 훌륭합니다 👏 👏 👏
ㅜㅜㅜ
